### ISSUE TITLE
Error About Incorrect Checksum When Applying Certain Patches

### ISSUE THREAD

**Issue by vector-man** [rameshvarun/ups#1]
Steps: 

1. Create a text file with the text "A" in it.
2. Create a text file with the text "B" in it.
3. Create a patch where "A" is the base and B is the modified.
4. Apply the resulting patch back to base "A"

Result: "Patch result did not have expected checksum"

OS: Windows 10 x64

**Comment by vector-man** [comment]
Nevermind! I did something wrong. I'll investigate before I close this. Thanks for the cool util!

**Comment by vector-man** [comment]
Sure enough, it does fail. 

Commands used:

`ups diff -b "C:\Users\Michael\Documents\Platform Test\A.txt" -m "C:\Users\Michael\Documents\Platform Test\B.txt" -o "C:\Users\Michael\Documents\Platform Test\B.ups"`

`ups apply -b "C:\Users\Michael\Documents\Platform Test\A.txt" -p "C:\Users\Michael\Documents\Platform Test\B.ups" -o "C:\Users\Michael\Documents\Platform Test\B_patched"`

Output: 

```
panic: Patch result did not have expected checksum
goroutine 1 [running]:
main.main.func1(0xc08206e0f0)
        /go/src/github.com/rameshvarun/ups/main.go:71 +0x32e
github.com/codegangsta/cli.Command.Run(0x5bb240, 0x5, 0x0, 0x0, 0xc08200e3c0, 0x1, 0x1, 0x5e0100, 0x1d, 0x0, ...)
        /go/src/github.com/codegangsta/cli/command.go:127 +0x1059
github.com/codegangsta/cli.(*App).Run(0xc082054100, 0xc082002080, 0x8, 0x8, 0x0, 0x0)
        /go/src/github.com/codegangsta/cli/app.go:159 +0xc36
main.main()
        /go/src/github.com/rameshvarun/ups/main.go:129 +0x96c
```

**Comment by vector-man** [comment]
Commands used:

`ups diff -b "C:\Users\Michael\Documents\Platform Test\A.txt" -m "C:\Users\Michael\Documents\Platform Test\B.txt" -o "C:\Users\Michael\Documents\Platform Test\B.ups"`

`ups apply -b "C:\Users\Michael\Documents\Platform Test\A.txt" -p "C:\Users\Michael\Documents\Platform Test\B.ups" -o "C:\Users\Michael\Documents\Platform Test\B_patched"`

**Comment by rameshvarun** [comment]
Thanks for reporting this - there was actually a pretty significant bug in the diffing code that applied to any situation where the last byte of a file was modified. I've fixed this issue in -
 cd8edd787b40682f95a9b0942538e3386019eb81. The latest version can be downloaded from https://github.com/rameshvarun/ups/releases/tag/v0.2.0.

**Comment by vector-man** [comment]
Great! Thanks for the quick fix!
